
package Vista;

import DaoTables.DaoProductos;
import DaoTables.DaoVentas;
import Tablas.Productos;
import Tablas.Ventas;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class IndexVentas extends javax.swing.JInternalFrame {

    DefaultListModel modelo = new DefaultListModel();
    
    private void crearModelo() throws SQLException{
        modelo.clear();
        List<Ventas> listaVentas = new ArrayList();
        listaVentas = DaoVentas.ventasLista();
        
        for(Ventas ventas:listaVentas){
            modelo.addElement(ventas);
        }
    }
    public IndexVentas() {
        initComponents();
        try{
            this.crearModelo();       
        }catch(SQLException ex){
            Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE,null,ex);
        }
        jList1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ventas");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Nombre del cliente");

        jLabel2.setText("Descuento");

        jLabel3.setText("Total de la venta");

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(evt.getClickCount()==2){
            int index = jList1.getSelectedIndex();
            Ventas ventas = (Ventas)modelo.getElementAt(index);
            try{
                DaoVentas.eliminar(ventas);
            }catch(SQLException ex){
                Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE, null,ex);
            }
            finally{
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                
                try{
                    this.crearModelo();
                }catch(SQLException ex){
                    Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE, null,ex);
                }
                jList1.setModel(modelo);
            }
        }
        
        else{
            int index = jList1.getSelectedIndex();
            Ventas ventas = (Ventas)modelo.getElementAt(index);
            jTextField1.setText(ventas.getNombreCliente());
            jTextField2.setText(""+ventas.getDescuento());
            jTextField3.setText(""+ventas.getTotalVenta());
            
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreCliente = jTextField1.getText();
        double descuento = jTextField2.getWidth();
        double totalVenta = jTextField3.getWidth();
        Ventas ventas = new Ventas(nombreCliente, totalVenta, descuento);
        
        try{
            DaoVentas.insertar(ventas);
        }catch(SQLException ex){
            Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE, null,ex);
        }
        finally{
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            
            try{
                this.crearModelo();
            }catch(SQLException ex){
                Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE, null,ex);
            }
            jList1.setModel(modelo);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String nombreCliente = jTextField1.getText();
            double descuento = jTextField2.getWidth();
            double totalVenta = jTextField3.getWidth();
            Ventas ventas = new Ventas(nombreCliente, totalVenta, descuento);
        
            try{
            DaoVentas.modificar(ventas);
        }catch(SQLException ex){
            Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE, null,ex);
        }
        finally{
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            //jTextField4.setText("");
            try{
                this.crearModelo();
            }catch(SQLException ex){
                Logger.getLogger(IndexVentas.class.getName()).log(Level.SEVERE, null,ex);
            }
            jList1.setModel(modelo);
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
